CREATE TABLE [conifer].[CLAIM] (
    [DOB]                               DATE            NULL,
    [Gender]                            VARCHAR (1)     NULL,
    [MemID]                             VARCHAR (12)    NULL,
    [ClaimNo]                           VARCHAR (20)    NULL,
    [ClaimLine]                         VARCHAR (3)     NULL,
    [PriorClaimNo]                      VARCHAR (40)    NULL,
    [AdjustmentCode]                    VARCHAR (6)     NULL,
    [AdjustmentDesc]                    VARCHAR (100)   NULL,
    [AuthNo]                            VARCHAR (25)    NULL,
    [SystemSource]                      VARCHAR (19)    NULL,
    [ProviderContractStatus]            VARCHAR (29)    NULL,
    [ProviderClass]                     VARCHAR (26)    NULL,
    [CoverageClass]                     VARCHAR (3)     NULL,
    [NetworkStatus]                     VARCHAR (1)     NULL,
    [ClaimLineServiceFromDate]          DATE            NULL,
    [AdmitDate]                         DATE            NULL,
    [DischargeDate]                     DATE            NULL,
    [PaidDate]                          DATE            NULL,
    [ReceivedDate]                      DATE            NULL,
    [BillingFromDate]                   DATE            NULL,
    [BillingToDate]                     DATE            NULL,
    [DeniedFlag]                        VARCHAR (1)     NULL,
    [TypeofBillCode]                    VARCHAR (3)     NULL,
    [RevenueCode]                       VARCHAR (15)    NULL,
    [Provider]                          VARCHAR (42)    NULL,
    [VendorID]                          VARCHAR (11)    NULL,
    [VendorName]                        VARCHAR (100)   NULL,
    [SecondaryPayerFlag]                VARCHAR (1)     NULL,
    [CapitatedServiceFlag]              VARCHAR (1)     NULL,
    [CapitationAmount]                  MONEY           NULL,
    [CheckNo]                           VARCHAR (7)     NULL,
    [EFTNo]                             VARCHAR (7)     NULL,
    [BilledAmount]                      MONEY           NULL,
    [AllowedAmount]                     MONEY           NULL,
    [PatientLiabilityAmount]            MONEY           NULL,
    [CoinsAmount]                       MONEY           NULL,
    [COBAmount]                         MONEY           NULL,
    [CopayAmount]                       MONEY           NULL,
    [DeductibleAmount]                  MONEY           NULL,
    [WithholdAmount]                    MONEY           NULL,
    [InterestAmount]                    MONEY           NULL,
    [PaidAmount]                        MONEY           NULL,
    [POS]                               VARCHAR (2)     NULL,
    [TypeofServiceCode]                 VARCHAR (1)     NULL,
    [AdmitSource]                       VARCHAR (1)     NULL,
    [AdmitType]                         VARCHAR (1)     NULL,
    [POAIndicator]                      VARCHAR (1)     NULL,
    [ProviderSpecialtyCode]             VARCHAR (3)     NULL,
    [ProviderTypeCode]                  VARCHAR (2)     NULL,
    [OrderingProviderNPI]               VARCHAR (10)    NULL,
    [OrderingProviderAddressLine]       VARCHAR (90)    NULL,
    [OrderingProviderAddressCity]       VARCHAR (30)    NULL,
    [OrderingProviderState]             VARCHAR (2)     NULL,
    [OrderingProviderZip]               VARCHAR (9)     NULL,
    [BillingProviderNPI]                VARCHAR (12)    NULL,
    [BillingProviderAddressLine]        VARCHAR (90)    NULL,
    [BillingProviderAddressCity]        VARCHAR (40)    NULL,
    [BillingProviderState]              VARCHAR (2)     NULL,
    [BillingProviderZip]                VARCHAR (9)     NULL,
    [PCPName]                           VARCHAR (200)   NULL,
    [PCPNPI]                            VARCHAR (11)    NULL,
    [PCPAddressLine]                    VARCHAR (90)    NULL,
    [PCPAddressCity]                    VARCHAR (19)    NULL,
    [PCPState]                          VARCHAR (2)     NULL,
    [PCPZip]                            VARCHAR (9)     NULL,
    [ReferringProviderNPI]              VARCHAR (12)    NULL,
    [ReferringProviderAddressLine]      VARCHAR (100)   NULL,
    [ReferringProviderAddressCity]      VARCHAR (50)    NULL,
    [ReferringProviderState]            VARCHAR (2)     NULL,
    [ReferringProviderZip]              VARCHAR (9)     NULL,
    [ServicingProviderNPI]              VARCHAR (12)    NULL,
    [ServicingProviderAddressLine]      VARCHAR (100)   NULL,
    [ServicingProviderAddressCity]      VARCHAR (50)    NULL,
    [ServicingProviderState]            VARCHAR (2)     NULL,
    [ServicingProviderZip]              VARCHAR (9)     NULL,
    [AdmittingPhysicianNPI]             VARCHAR (12)    NULL,
    [AdmittingProviderAddressLine]      VARCHAR (100)   NULL,
    [AdmittingProviderAddressCity]      VARCHAR (50)    NULL,
    [AdmittingProviderState]            VARCHAR (2)     NULL,
    [AdmittingProviderZip]              VARCHAR (9)     NULL,
    [ProcCode]                          VARCHAR (11)    NULL,
    [Modifier]                          VARCHAR (2)     NULL,
    [DRGOutlier]                        VARCHAR (4)     NULL,
    [DRGSeverity]                       VARCHAR (1)     NULL,
    [DischargeStatusCode]               VARCHAR (2)     NULL,
    [DRGCode]                           VARCHAR (3)     NULL,
    [DRGVersion]                        VARCHAR (3)     NULL,
    [DXVer]                             VARCHAR (1)     NULL,
    [DX1]                               VARCHAR (7)     NULL,
    [DX2]                               VARCHAR (7)     NULL,
    [DX3]                               VARCHAR (7)     NULL,
    [DX4]                               VARCHAR (7)     NULL,
    [DX5]                               VARCHAR (7)     NULL,
    [DX6]                               VARCHAR (7)     NULL,
    [DX7]                               VARCHAR (7)     NULL,
    [DX8]                               VARCHAR (7)     NULL,
    [DX9]                               VARCHAR (7)     NULL,
    [DX10]                              VARCHAR (7)     NULL,
    [PROCDX1Detail]                     VARCHAR (15)    NULL,
    [PROCDX2Detail]                     VARCHAR (15)    NULL,
    [PROCDX3Detail]                     VARCHAR (15)    NULL,
    [PROCDX4Detail]                     VARCHAR (15)    NULL,
    [PROCDX5Detail]                     VARCHAR (15)    NULL,
    [PROCDX6Detail]                     VARCHAR (15)    NULL,
    [PROCDX7Detail]                     VARCHAR (15)    NULL,
    [PROCDX8Detail]                     VARCHAR (15)    NULL,
    [PROCDX9Detail]                     VARCHAR (15)    NULL,
    [PROCDX10Detail]                    VARCHAR (15)    NULL,
    [NDCCode]                           VARCHAR (11)    NULL,
    [BrandName]                         VARCHAR (100)   NULL,
    [GenericName]                       VARCHAR (100)   NULL,
    [NDCDosage]                         VARCHAR (3)     NULL,
    [NDCStrength]                       VARCHAR (10)    NULL,
    [NDCRoute]                          VARCHAR (3)     NULL,
    [Quantity]                          FLOAT (53)      NULL,
    [Notes]                             VARCHAR (5000)  NULL,
    [HospitalName]                      VARCHAR (42)    NULL,
    [PlanID]                            VARCHAR (8)     NULL,
    [EffDate]                           DATE            NULL,
    [TermDate]                          DATE            NULL,
    [MemberFirstName]                   VARCHAR (18)    NULL,
    [MemberLastName]                    VARCHAR (32)    NULL,
    [PlanName]                          VARCHAR (4)     NULL,
    [Dyad]                              VARCHAR (45)    NULL,
    [ProcedureNotes]                    NVARCHAR (4000) NULL,
    [QCNotes]                           NVARCHAR (4000) NULL,
    [RxInformation]                     NVARCHAR (4000) NULL,
    [COB]                               VARCHAR (40)    NULL,
    [NPI]                               VARCHAR (11)    NULL,
    [PROCDX11Detail]                    VARCHAR (15)    NULL,
    [PROCDX12Detail]                    VARCHAR (15)    NULL,
    [PROCDX13Detail]                    VARCHAR (15)    NULL,
    [PROCDX14Detail]                    VARCHAR (15)    NULL,
    [PROCDX15Detail]                    VARCHAR (15)    NULL,
    [PROCDX16Detail]                    VARCHAR (15)    NULL,
    [PROCDX17Detail]                    VARCHAR (15)    NULL,
    [PROCDX18Detail]                    VARCHAR (15)    NULL,
    [PROCDX19Detail]                    VARCHAR (15)    NULL,
    [PROCDX20Detail]                    VARCHAR (15)    NULL,
    [PROCDX21Detail]                    VARCHAR (15)    NULL,
    [PROCDX22Detail]                    VARCHAR (15)    NULL,
    [PROCDX23Detail]                    VARCHAR (15)    NULL,
    [PROCDX24Detail]                    VARCHAR (15)    NULL,
    [PROCDX25Detail]                    VARCHAR (15)    NULL,
    [DX11]                              VARCHAR (7)     NULL,
    [DX12]                              VARCHAR (7)     NULL,
    [DX13]                              VARCHAR (7)     NULL,
    [DX14]                              VARCHAR (7)     NULL,
    [DX15]                              VARCHAR (7)     NULL,
    [DX16]                              VARCHAR (7)     NULL,
    [DX17]                              VARCHAR (7)     NULL,
    [DX18]                              VARCHAR (7)     NULL,
    [DX19]                              VARCHAR (7)     NULL,
    [DX20]                              VARCHAR (7)     NULL,
    [DX21]                              VARCHAR (7)     NULL,
    [DX22]                              VARCHAR (7)     NULL,
    [DX23]                              VARCHAR (7)     NULL,
    [DX24]                              VARCHAR (7)     NULL,
    [DX25]                              VARCHAR (7)     NULL,
    [ClaimLineServiceToDate]            DATE            NULL,
    [ProcCodeModifier2]                 VARCHAR (2)     NULL,
    [ProcCodeModifier3]                 VARCHAR (2)     NULL,
    [ProcCodeModifier4]                 VARCHAR (2)     NULL,
    [ConditionsCode01]                  VARCHAR (2)     NULL,
    [ConditionsCode02]                  VARCHAR (2)     NULL,
    [ConditionsCode03]                  VARCHAR (2)     NULL,
    [ConditionsCode04]                  VARCHAR (2)     NULL,
    [ConditionsCode05]                  VARCHAR (2)     NULL,
    [ConditionsCode06]                  VARCHAR (2)     NULL,
    [ConditionsCode07]                  VARCHAR (2)     NULL,
    [ConditionsCode08]                  VARCHAR (2)     NULL,
    [ConditionsCode09]                  VARCHAR (2)     NULL,
    [ConditionsCode10]                  VARCHAR (2)     NULL,
    [OccurrenceCode01]                  VARCHAR (10)    NULL,
    [OccurrenceCode02]                  VARCHAR (2)     NULL,
    [OccurrenceCode03]                  VARCHAR (5)     NULL,
    [OccurrenceCode04]                  VARCHAR (4)     NULL,
    [OccurrenceCode05]                  VARCHAR (3)     NULL,
    [OccurrenceCode06]                  VARCHAR (21)    NULL,
    [OccurrenceCode07]                  VARCHAR (20)    NULL,
    [OccurrenceCode08]                  VARCHAR (10)    NULL,
    [OccurrenceCode09]                  VARCHAR (2)     NULL,
    [OccurrenceCode10]                  VARCHAR (9)     NULL,
    [LastChangeDate]                    VARCHAR (508)   NULL,
    [DiagPointer]                       VARCHAR (10)    NULL,
    [FinancialResponsibility]           VARCHAR (6)     NULL,
    [RefundAmount]                      MONEY           NULL,
    [BenefitMasterID]                   VARCHAR (10)    NULL,
    [BenefitMasterDesc]                 VARCHAR (45)    NULL,
    [VendorAddress]                     VARCHAR (200)   NULL,
    [VendorCity]                        VARCHAR (22)    NULL,
    [VendorState]                       VARCHAR (2)     NULL,
    [VendorZipCode]                     VARCHAR (9)     NULL,
    [ClaimNotes]                        VARCHAR (4919)  NULL,
    [RefundRequest1stLetterDate]        DATE            NULL,
    [MRN]                               VARCHAR (17)    NULL,
    [PatientControlNumber]              VARCHAR (25)    NULL,
    [ClaimFromDate]                     DATE            NULL,
    [ClaimToDate]                       DATE            NULL,
    [POSDetail]                         VARCHAR (2)     NULL,
    [ProcDX1]                           VARCHAR (15)    NULL,
    [ProcDX2]                           VARCHAR (15)    NULL,
    [ProcDX3]                           VARCHAR (15)    NULL,
    [ProcDX4]                           VARCHAR (15)    NULL,
    [ProcDX5]                           VARCHAR (15)    NULL,
    [ProcDX6]                           VARCHAR (15)    NULL,
    [ProcDX7]                           VARCHAR (15)    NULL,
    [ProcDX8]                           VARCHAR (15)    NULL,
    [ProcDX9]                           VARCHAR (15)    NULL,
    [ProcDX10]                          VARCHAR (15)    NULL,
    [ProcDX11]                          VARCHAR (15)    NULL,
    [ProcDX12]                          VARCHAR (15)    NULL,
    [ProcDX13]                          VARCHAR (15)    NULL,
    [ProcDX14]                          VARCHAR (15)    NULL,
    [ProcDX15]                          VARCHAR (15)    NULL,
    [ProcDX16]                          VARCHAR (15)    NULL,
    [ProcDX17]                          VARCHAR (15)    NULL,
    [ProcDX18]                          VARCHAR (15)    NULL,
    [ProcDX19]                          VARCHAR (15)    NULL,
    [ProcDX20]                          VARCHAR (15)    NULL,
    [ProcDX21]                          VARCHAR (15)    NULL,
    [ProcDX22]                          VARCHAR (15)    NULL,
    [ProcDX23]                          VARCHAR (15)    NULL,
    [ProcDX24]                          VARCHAR (15)    NULL,
    [ProcDX25]                          VARCHAR (15)    NULL,
    [AdjustmentCodeDetail]              VARCHAR (15)    NULL,
    [POAIndicator1]                     VARCHAR (1)     NULL,
    [POAIndicator2]                     VARCHAR (1)     NULL,
    [POAIndicator3]                     VARCHAR (1)     NULL,
    [POAIndicator4]                     VARCHAR (1)     NULL,
    [POAIndicator5]                     VARCHAR (1)     NULL,
    [POAIndicator6]                     VARCHAR (1)     NULL,
    [POAIndicator7]                     VARCHAR (1)     NULL,
    [POAIndicator8]                     VARCHAR (1)     NULL,
    [POAIndicator9]                     VARCHAR (1)     NULL,
    [POAIndicator10]                    VARCHAR (1)     NULL,
    [POAIndicator11]                    VARCHAR (1)     NULL,
    [POAIndicator12]                    VARCHAR (1)     NULL,
    [POAIndicator13]                    VARCHAR (1)     NULL,
    [POAIndicator14]                    VARCHAR (1)     NULL,
    [POAIndicator15]                    VARCHAR (1)     NULL,
    [POAIndicator16]                    VARCHAR (1)     NULL,
    [POAIndicator17]                    VARCHAR (1)     NULL,
    [POAIndicator18]                    VARCHAR (1)     NULL,
    [POAIndicator19]                    VARCHAR (1)     NULL,
    [POAIndicator20]                    VARCHAR (1)     NULL,
    [POAIndicator21]                    VARCHAR (1)     NULL,
    [POAIndicator22]                    VARCHAR (6)     NULL,
    [POAIndicator23]                    VARCHAR (5)     NULL,
    [POAIndicator24]                    VARCHAR (10)    NULL,
    [POAIndicator25]                    VARCHAR (4)     NULL,
    [MSDRGSeverity]                     VARCHAR (3)     NULL,
    [MSDRGSeverityWeight]               VARCHAR (3)     NULL,
    [APRDRG]                            VARCHAR (10)    NULL,
    [APRDRBWeight]                      VARCHAR (10)    NULL,
    [OtherInsuranceName]                VARCHAR (40)    NULL,
    [OtherInsurancePrime]               VARCHAR (9)     NULL,
    [ServicingProviderIDConifer]        VARCHAR (6)     NULL,
    [ContractStatus]                    VARCHAR (5)     NULL,
    [ContractEffectiveDate]             DATE            NULL,
    [ServicingProviderAccountNumber]    VARCHAR (4)     NULL,
    [ServicingProviderSubaccountNumber] VARCHAR (3)     NULL,
    [ServicingProviderSpecialty]        VARCHAR (3)     NULL,
    [ServicingProviderTaxonomyCode]     VARCHAR (10)    NULL,
    [BillingProviderTaxonomyCode]       VARCHAR (10)    NULL,
    [OrderingProviderTaxonomyCode]      VARCHAR (10)    NULL,
    [ReferringProviderTaxonomyCode]     VARCHAR (20)    NULL,
    [ServicingProviderTaxID]            VARCHAR (12)    NULL,
    [BillingProviderTaxID]              VARCHAR (12)    NULL,
    [OrderingProviderTaxID]             VARCHAR (12)    NULL,
    [ReferringProviderTaxID]            VARCHAR (12)    NULL,
    [ServicingProviderTypeDescription]  VARCHAR (200)   NULL,
    [BillingProviderTypeDescription]    VARCHAR (200)   NULL,
    [OrderingProviderTypeDescription]   VARCHAR (200)   NULL,
    [ReferringProviderTypeDescription]  VARCHAR (200)   NULL,
    [ConiferAuthID]                     VARCHAR (25)    NULL,
    [ExternalAuthID]                    VARCHAR (50)    NULL,
    [POSDetailDescr]                    VARCHAR (200)   NULL,
    [AdjustmentAmount]                  MONEY           NULL,
    [ClaimsImageReferenceID]            VARCHAR (30)    NULL,
    [RevenueRecoveryNotes]              VARCHAR (4000)  NULL,
    [RCRD_ORDR]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [RCRD_LOAD_DTTM]                    DATETIME        DEFAULT (getdate()) NOT NULL,
    [RCRD_LOAD_USER_NM]                 VARCHAR (50)    DEFAULT (user_name()) NOT NULL,
    [SRC_DATA_NM]                       VARCHAR (200)   NOT NULL
);

