CREATE TABLE [cms].[HCPCS_PROC_TOS_CODE] (
    [PROC_TOS_CODE]        VARCHAR (1)   NOT NULL,
    [PROC_TOS_DESCRIPTION] VARCHAR (200) NOT NULL,
    [RCRD_ORDR]            BIGINT        IDENTITY (1, 1) NOT NULL,
    [RCRD_LOAD_DTTM]       DATETIME      DEFAULT (getdate()) NOT NULL,
    [RCRD_LOAD_USER_NM]    VARCHAR (50)  DEFAULT (user_name()) NOT NULL,
    [SRC_DATA_NM]          VARCHAR (200) NOT NULL
);

