CREATE TABLE [cms].[POA_INDICATOR_CODE] (
    [POA_INDICATOR_CODE]        CHAR (1)      NOT NULL,
    [POA_INDICATOR_DESCRIPTION] VARCHAR (600) NULL,
    [RCRD_ORDR]                 BIGINT        IDENTITY (1, 1) NOT NULL,
    [RCRD_LOAD_DTTM]            DATETIME      DEFAULT (getdate()) NOT NULL,
    [RCRD_LOAD_USER_NM]         VARCHAR (50)  DEFAULT (user_name()) NOT NULL,
    [SRC_DATA_NM]               VARCHAR (200) NOT NULL
);

