CREATE TABLE [ch].[CALENDAR_DATE] (
    [DT_ID]             CHAR (8)      NOT NULL,
    [DT]                DATE          NOT NULL,
    [YR_STRT_DT]        DATE          NOT NULL,
    [YR_END_DT]         DATE          NOT NULL,
    [QTR_STRT_DT]       DATE          NOT NULL,
    [QTR_END_DT]        DATE          NOT NULL,
    [MNTH_STRT_DT]      DATE          NOT NULL,
    [MNTH_END_DT]       DATE          NOT NULL,
    [WK_STRT_DT]        DATE          NOT NULL,
    [WK_END_DT]         DATE          NOT NULL,
    [YR_NBR]            SMALLINT      NOT NULL,
    [QTR_ORDNL_NM]      CHAR (3)      NOT NULL,
    [QTR_NBR]           TINYINT       NOT NULL,
    [QTR_FULL_NM]       VARCHAR (14)  NOT NULL,
    [QTR_SHRT_NM]       CHAR (2)      NOT NULL,
    [MNTH_NBR]          TINYINT       NOT NULL,
    [MNTH_NM]           VARCHAR (9)   NOT NULL,
    [MNTH_SHRT_NM]      CHAR (3)      NOT NULL,
    [WK_NBR]            TINYINT       NOT NULL,
    [DAY_NBR]           SMALLINT      NOT NULL,
    [DAY_NM]            VARCHAR (9)   NOT NULL,
    [DAY_SHRT_NM]       CHAR (3)      NOT NULL,
    [IS_WKND_IND]       BIT           NOT NULL,
    [IS_HLDY_IND]       BIT           NOT NULL,
    [IS_MSO_HLDY_IND]   BIT           NOT NULL,
    [HLDY_NM]           VARCHAR (60)  NOT NULL,
    [RCRD_ORDR]         BIGINT        IDENTITY (1, 1) NOT NULL,
    [RCRD_LOAD_DTTM]    DATETIME      DEFAULT (getdate()) NOT NULL,
    [RCRD_LOAD_USER_NM] VARCHAR (50)  DEFAULT (user_name()) NOT NULL,
    [SRC_DATA_NM]       VARCHAR (200) NOT NULL
);

