CREATE TABLE [resdac].[ADMIT_TYPE_CODE] (
    [ADMIT_TYPE_CODE]        TINYINT       NOT NULL,
    [ADMIT_TYPE_DESCRIPTION] VARCHAR (50)  NULL,
    [ADMIT_TYPE_DETAIL]      VARCHAR (300) NULL,
    [RCRD_ORDR]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [RCRD_LOAD_DTTM]         DATETIME      DEFAULT (getdate()) NOT NULL,
    [RCRD_LOAD_USER_NM]      VARCHAR (50)  DEFAULT (user_name()) NOT NULL,
    [SRC_DATA_NM]            VARCHAR (200) NOT NULL
);

