CREATE TABLE [resdac].[ADMIT_SOURCE_CODE] (
    [ADMIT_SOURCE_CODE]        VARCHAR (1)   NOT NULL,
    [ADMIT_SOURCE_DESCRIPTION] VARCHAR (260) NULL,
    [RCRD_ORDR]                BIGINT        IDENTITY (1, 1) NOT NULL,
    [RCRD_LOAD_DTTM]           DATETIME      DEFAULT (getdate()) NOT NULL,
    [RCRD_LOAD_USER_NM]        VARCHAR (50)  DEFAULT (user_name()) NOT NULL,
    [SRC_DATA_NM]              VARCHAR (200) NOT NULL
);

